`default_nettype none
module dist_rom_board_top (
    input  wire [3:0] SW,
    output wire [7:0] LED
);
    // Generated by create_project.tcl as a Distributed Memory Generator ROM.
    dist_rom16 u_rom (
        .a(SW),
        .spo(LED)
    );
endmodule
`default_nettype wire
