`default_nettype none
module block_rom_board_top (
    input  wire       CLK100MHZ,
    input  wire [2:0] SW,
    output wire [6:0] SEG,
    output wire [7:0] AN,
    output wire       DP
);
    wire [15:0] word_data;

    // Generated by create_project.tcl as a single-port Block ROM.
    block_rom8x16 u_rom (
        .clka(CLK100MHZ),
        .addra(SW),
        .douta(word_data)
    );

    sevenseg_hex u_display (
        .clk(CLK100MHZ),
        .data(word_data),
        .seg(SEG),
        .an(AN),
        .dp(DP)
    );
endmodule
`default_nettype wire
